#!/usr/bin/sh
mount -o bind /usr/bin /bin
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tmp
mount -t proc proc /proc
mount -t sysfs sysfs /sys
ip addr add 10.0.2.15/24 dev eth0
ip link set eth0 up
ip route add default via 10.0.2.2 dev eth0
date -s "2024-01-21 00:00:00"
echo "starting shell"
exec sh
